### ISSUE TITLE
Callback never called

### ISSUE THREAD

**Issue by Alkashi** [sumup/sumup-ecom-php-sdk#20]
Hi,

I use this sdk to generate checkout and accept payment on a mobile app via the sumup card widget that can be found here https://developer.sumup.com/docs/widgets-card/

My process is the following : 

1. The user open my app and press the "Pay by card" button : a request to the server is done to generate the checkout thanks to this sdk and I indicate a callback URL like this
$checkoutService = $sumup->getCheckoutService();
$checkoutResponse = $checkoutService->create($amount, $currency, $checkoutRef, $payToEmail, $emailClient, null, $callBackUrl);

3. The checkout id is retreived and the url of the page containing the card widget is generated and displayed on a  webview on my app

4. The user enter his card number, the validation is done and the user is asked to validate the 3DS process

5. Some users must validate the 3DS process on their bank app => MY mobile app is on background

The pb is if the user never reopen my app, the payment is never validated because the callback is never called.

Is there a way to make the process completed even if the user never re open my app and display the webview to complete the process ?

Many thanks in advance.

**Comment by ptrovatelli** [comment]
I haven't tried on mobile yet, but on PC I don't need to set a callback url in the checkout. The widget can handle the callback like so: 
```
<script type="text/javascript">
    SumUpCard.mount({
        checkoutId: '<?php echo $checkoutId; ?>',
        onResponse: function(type, body) {
            // ref: https://developer.sumup.com/docs/widgets-card/
            console.log('Type', type);
            console.log('Body', body);
            if(type === 'success'){
                window.location.href = 'https://...';
            }
        }
    });
```

You can add a case for type error too, although I haven't come across this case yet - but i'm still working with a test account (even when the payment is canceled, the widget gets a success type).

**Comment by joelrose** [comment]
If you still experience this issue, please open another issue!

**Comment by MariaMozgunova** [comment]
> I haven't tried on mobile yet, but on PC I don't need to set a callback url in the checkout. The widget can handle the callback like so:
> 
> ```
> <script type="text/javascript">
>     SumUpCard.mount({
>         checkoutId: '<?php echo $checkoutId; ?>',
>         onResponse: function(type, c) {
>             // ref: https://developer.sumup.com/docs/widgets-card/
>             console.log('Type', type);
>             console.log('Body', body);
>             if(type === 'success'){
>                 window.location.href = 'https://...';
>             }
>         }
>     });
> ```
> 
> You can add a case for type error too, although I haven't come across this case yet - but i'm still working with a test account (even when the payment is canceled, the widget gets a success type).

I also experience the issue that the callback URL is never called.
The suggested solution might not be very safe. When you redirect the user and also pass `body`. The client side might change the contents of the `body` variable.

**Comment by ptrovatelli** [comment]
@MariaMozgunova of course you cannot use the front to make security decisions. I use this only to send a signal that the transaction is supposedly finished. Then I call sumup servers to check the transaction status. I also have a cron scheduled to cover the cases where the signal was not sent like browser closed or connection lost but that takes much longer to proceed

**Comment by MariaMozgunova** [comment]
@ptrovatelli 
Making a call over the network introduces a time delay. Looks like it can only be done asynchronously.
It would be much better in terms of time performance if SumUp called the callback URL. You wouldn't want the paying customer to wait long to show a success/failure message. It also eliminates the need to write a cron job.

Looks like the best option would be to redirect the customer to a page saying if the transaction succeeded or failed based on the `body` of `onResponse` callback. And then process the transaction on the backend asynchronously.

**Comment by ptrovatelli** [comment]
@MariaMozgunova the time overhead is pretty small but I agree it would be simpler if the callback url were called by sumup 😀. This issue was maybe closed a bit too quickly, my answer was not really the solution, just a workaround. If the callback url is never called then at least the doc ought to be updated to remove that feature which actually doesn't exist

**Comment by ptrovatelli** [comment]
@MariaMozgunova actually there is no more "callback url" in the documentation. it's now a `returnURL` but it doesn't really say what it's supposed to do. 
https://github.com/sumup/sumup-ecom-php-sdk/blob/master/docs/reference/Checkouts.md 

Initially I though it was a backend call from sumup servers to our backend (which was mabe the goal of the "callback url") but now it's where the client is redirected to after the 3d secure. see https://github.com/sumup/sumup-ecom-php-sdk/releases/tag/1.2.0
```
This release introduces a possibility to create a Checkout with the redirect_url field specified. This field defines where a payer to be taken after completing external actions required to complete a payment, such as 3DS authentication.
```

Still if the client doesn't go back to the app (which was op's initial issue) or if the client has closed the browser we need a way to force the transaction verification and completion. Thus the cron. I don't think it could be done differently


And about:
>> Looks like the best option would be to redirect the customer to a page saying if the transaction succeeded or failed based on the body of onResponse callback.

the widget does display the status of the transaction. But you need in any case to make backend call to verify the transaction. I just trigger that backend to backend verification from the onResponse so that I can redirect the user to the proper page in my app (sucess page or error page depending on the transaction status, not depending on the "sucess" or "error" type as this one is not always correct in my experience). Now it probably works with that new `returnUrl` field rather than explicitely using `window.location.href `
